development:
  adapter: postgresql
  database: database.db

test:
    adapter: postgresql

  database: database.db

production:
  adapter: postgresql
  database: mission
  username: username
  password: password
  host: localhost